// src/data/LivePageData.js
export const liveData = [
  {
    id: 1,
    tabCategory: "팔로잉",
    topText: "Now Live!",
    topTextColor: "#fff",
    image: "/img/following1.svg",
    label: "HOT",
    labelColor: "#ff4d4d",
    smallImage: "/img/my-artist-1.png",
    subTitle: "10초 하이라이트 클립",
    group: "HONEYZ",
    member: "제이",
    url: "https://www.twitch.tv/team/projecti",
  },
  {
    id: 2,
    tabCategory: "팔로잉",
    topText: "Live Replay",
    topTextColor: "#fff",
    image: "/img/following2.svg",
    label: "HOT",
    labelColor: "#ff4d4d",
    smallImage: "/img/my-artist-1.png",
    subTitle: "오늘의 라이브 요약",
    group: "HONEYZ",
    member: "제이",
    url: "https://www.twitch.tv/team/projecti",
  },
  {
    id: 3,
    tabCategory: "팔로잉",
    topText: "Recommended",
    topTextColor: "#fff",
    image: "/img/following3.svg",
    label: "NEW",
    labelColor: "#2ecc71",
    smallImage: "/img/my-artist-1.png",
    subTitle: "비하인드 콘텐츠 모음.zip",
    group: "LUVITA",
    member: "이이네",
    url: "https://www.sooplive.co.kr/station/luvita",
  },
  {
    id: 4,
    tabCategory: "라이브",
    topText: "Live Replay",
    topTextColor: "#fff",
    image: "/img/live1.svg",
    label: "NEW",
    labelColor: "#2ecc71",
    smallImage: "/img/my-artist-1.png",
    subTitle: "당신을 위한 추천 라이브",
    group: "IRISE",
    member: "이이네",
    url: "https://weverse.io/irise/live",
  },
  {
    id: 5,
    tabCategory: "라이브",
    topText: "Live Replay",
    topTextColor: "#fff",
    image: "/img/live2.svg",
    label: "NEW",
    labelColor: "#2ecc71",
    smallImage: "/img/my-artist-1.png",
    subTitle: "지금 가장 트렌디한 순간",
    group: "PLAVE",
    member: "밤비",
    url: "https://weverse.io/plave/live?hl=ko",
  },
  {
    id: 6,
    tabCategory: "라이브",
    topText: "Live Replay",
    topTextColor: "#fff",
    image: "/img/live3.svg",
    label: "NEW",
    labelColor: "#2ecc71",
    smallImage: "/img/my-artist-1.png",
    subTitle: "무대 풀캠 리플레이",
    group: "PLAVE",
    member: "밤비",
    url: "https://weverse.io/plave/live?hl=ko",
  },
  {
    id: 7,
    tabCategory: "라이브",
    topText: "Live Replay",
    topTextColor: "#fff",
    image: "/img/live4.svg",
    label: "NEW",
    labelColor: "#2ecc71",
    smallImage: "/img/my-artist-1.png",
    subTitle: "리액션 모음 클립",
    group: "LUVITA",
    member: "아이비",
    url: "https://www.sooplive.co.kr/station/luvita",
  },
  {
    id: 8,
    tabCategory: "콘텐츠",
    topText: "Hot Issue",
    topTextColor: "#3498db",
    image: "/img/content1.svg",
    label: "NEW",
    labelColor: "#2ecc71",
    smallImage: "/img/my-artist-1.png",
    subTitle: "FOR YOU 추천 클립",
    group: "IRISE",
    member: "이이네",
    url: "https://weverse.io/plave/live?hl=ko",
  },
  {
    id: 9,
    tabCategory: "콘텐츠",
    topText: "New Content",
    topTextColor: "#3498db",
    image: "/img/content2.svg",
    label: "NEW",
    labelColor: "#2ecc71",
    smallImage: "/img/my-artist-1.png",
    subTitle: "TREND 밈 클립",
    group: "PLAVE",
    member: "밤비",
    url: "https://weverse.io/plave/live?hl=ko",
  },
  {
    id: 10,
    tabCategory: "콘텐츠",
    topText: "For You",
    topTextColor: "#3498db",
    image: "/img/content3.svg",
    label: "NEW",
    labelColor: "#2ecc71",
    smallImage: "/img/my-artist-1.png",
    subTitle: "산중 호걸이라는 테리님의 생일날 멤버들에...",
    group: "LUVITA",
    member: "이이네",
    url: "https://www.sooplive.co.kr/station/luvita",
  },
  {
    id: 11,
    tabCategory: "콘텐츠",
    topText: "Trend on NOVA",
    topTextColor: "#3498db",
    image: "/img/content4.svg",
    label: "NEW",
    labelColor: "#2ecc71",
    smallImage: "/img/my-artist-1.png",
    subTitle: "킬링파트 모음",
    group: "PLAVE",
    member: "하민",
    url: "https://weverse.io/plave/live?hl=ko",
  },
];
