// src/data/LivePageData.js
export const liveData = [
  {
    id: 1,
    tabCategory: "팔로잉",
    topText: "Now Live!",
    topTextColor: "#fff",
    image: "/img/following1.svg",
    label: "HOT",
    labelColor: "#ff4d4d",
    smallImage: "/img/my-artist-list2.svg",
    subTitle: "산중 호걸이라는 테리님의 생일날 멤버들에...",
    group: "LUVDIA",
    member: "이이네",
  },
  {
    id: 2,
    tabCategory: "팔로잉",
    topText: "Live Replay",
    topTextColor: "#fff",
    image: "/img/following2.svg",
    label: "HOT",
    labelColor: "#ff4d4d",
    smallImage: "/img/my-artist-list2.svg",
    subTitle: "산중 호걸이라는 테리님의 생일날 멤버들에...",
    group: "LUVDIA",
    member: "이이네",
  },
  {
    id: 3,
    tabCategory: "팔로잉",
    topText: "Recommended",
    topTextColor: "#fff",
    image: "/img/following3.svg",
    label: "NEW",
    labelColor: "#2ecc71",
    smallImage: "/img/my-artist-list2.svg",
    subTitle: "산중 호걸이라는 테리님의 생일날 멤버들에...",
    group: "LUVDIA",
    member: "이이네",
  },
  {
    id: 4,
    tabCategory: "라이브",
    topText: "Live Replay",
    topTextColor: "#fff",
    image: "/img/live1.svg",
    label: "NEW",
    labelColor: "#2ecc71",
    smallImage: "/img/my-artist-list2.svg",
    subTitle: "산중 호걸이라는 테리님의 생일날 멤버들에...",
    group: "LUVDIA",
    member: "이이네",
  },
  {
    id: 5,
    tabCategory: "라이브",
    topText: "Live Replay",
    topTextColor: "#fff",
    image: "/img/live2.svg",
    label: "NEW",
    labelColor: "#2ecc71",
    smallImage: "/img/my-artist-list2.svg",
    subTitle: "산중 호걸이라는 테리님의 생일날 멤버들에...",
    group: "LUVDIA",
    member: "이이네",
  },
  {
    id: 6,
    tabCategory: "라이브",
    topText: "Live Replay",
    topTextColor: "#fff",
    image: "/img/live3.svg",
    label: "NEW",
    labelColor: "#2ecc71",
    smallImage: "/img/my-artist-list2.svg",
    subTitle: "산중 호걸이라는 테리님의 생일날 멤버들에...",
    group: "LUVDIA",
    member: "이이네",
  },
  {
    id: 7,
    tabCategory: "라이브",
    topText: "Live Replay",
    topTextColor: "#fff",
    image: "/img/live4.svg",
    label: "NEW",
    labelColor: "#2ecc71",
    smallImage: "/img/my-artist-list2.svg",
    subTitle: "산중 호걸이라는 테리님의 생일날 멤버들에...",
    group: "LUVDIA",
    member: "이이네",
  },
  {
    id: 8,
    tabCategory: "콘텐츠",
    topText: "Hot Issue",
    topTextColor: "#3498db",
    image: "/img/content1.svg",
    label: "NEW",
    labelColor: "#2ecc71",
    smallImage: "/img/my-artist-list2.svg",
    subTitle: "산중 호걸이라는 테리님의 생일날 멤버들에...",
    group: "LUVDIA",
    member: "이이네",
  },
  {
    id: 9,
    tabCategory: "콘텐츠",
    topText: "New Content",
    topTextColor: "#3498db",
    image: "/img/content2.svg",
    label: "NEW",
    labelColor: "#2ecc71",
    smallImage: "/img/my-artist-list2.svg",
    subTitle: "산중 호걸이라는 테리님의 생일날 멤버들에...",
    group: "LUVDIA",
    member: "이이네",
  },
  {
    id: 10,
    tabCategory: "콘텐츠",
    topText: "For You",
    topTextColor: "#3498db",
    image: "/img/content3.svg",
    label: "NEW",
    labelColor: "#2ecc71",
    smallImage: "/img/my-artist-list2.svg",
    subTitle: "산중 호걸이라는 테리님의 생일날 멤버들에...",
    group: "LUVDIA",
    member: "이이네",
  },
  {
    id: 11,
    tabCategory: "콘텐츠",
    topText: "Trend on NOVA",
    topTextColor: "#3498db",
    image: "/img/content4.svg",
    label: "NEW",
    labelColor: "#2ecc71",
    smallImage: "/img/my-artist-list2.svg",
    subTitle: "산중 호걸이라는 테리님의 생일날 멤버들에...",
    group: "LUVDIA",
    member: "이이네",
  },
];
